CREATE TABLE IF NOT EXISTS affiliated_clubs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  state VARCHAR(150) NOT NULL,
  region VARCHAR(200),
  club_name VARCHAR(300) NOT NULL,
  location VARCHAR(300),
  contact_info VARCHAR(300),
  email VARCHAR(200),
  notes TEXT,
  sort_order INT DEFAULT 0,
  is_active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
